language: ruby

branches:
  only:
    - master

before_install:
  - gem install bundler
  - bundle install

script:
  - bundle exec jekyll build

after_success:
  - cd _site
  - git init
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add .
  - git commit -m "travis-build $TRAVIS_BUILD_NUMBER"
  - git remote add origin https://${GITHUB_TOKEN}@github.com/murihpusparum/murihpusparum.github.io.git > /dev/null 2>&1 
  - git push --force --quiet --set-upstream origin master
