# Site settings
title: Hyde
email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://yourdomain.com"
asseturl: "/assets/"
keywords: 'your, site, keyword, used, for, meta, keywords'
facebook_username: yourfacebookusername
twitter_username: yourtwitterusername
github_username:  yourgithubusername
linkedin_username: yourlinkedinusername
google_site_verification: whatever

# Article settings
name: Hyde
author: Your Website Author
author_desc: >
  Write your author description for your new site here. You can edit this
  line in _config.yml. It will appear in every post you made.

# Build settings
gem:
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
gems: [jekyll-paginate]
markdown: kramdown
paginate: 15
paginate_path: "paginate/:num/"
exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
  - license.md
  - bower_components
  - node_modules
  - _js

# Jekyll archive setting
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
    - month
  layout: 'archive'
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'
    year: '/:year/'
    month: '/:year/:month/'    
