# Site settings
title: Murih Pusparum
email: murihpusparum@gmail.com
description: >
  Suka banget sama kucing, yang di atas ini anaknya ibu namanya Uno.
baseurl: ""
url: "http://www.murihpusparum.net"
asseturl: "/assets/"
keywords: 'your, site, keyword, used, for, meta, keywords'
facebook_username: yourfacebookusername
twitter_username: yourtwitterusername
github_username:  yourgithubusername
linkedin_username: yourlinkedinusername
google_site_verification: whatever

# Build settings
gem:
  - jekyll-sitemap
  - jekyll-paginate
gems: [jekyll-paginate]
markdown: kramdown
paginate: 16
paginate_path: "paginate/:num/"
exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
  - license.md
  - bower_components
  - node_modules
  - _js
  - _sass

# Jekyll archive setting
# jekyll-archives:
#   enabled:
#     - year
#     - month
#   layout: 'archive'
#   permalinks:
#     tag: '/tag/:name/'
#     category: '/category/:name/'
#     year: '/:year/'
#     month: '/:year/:month/'    
